/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/crt_monitor.glb 
Author: James.Harness (https://sketchfab.com/James.Harness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crt-monitor-e2dd2887a8904e4fa3d5a32e2935adb9
Title: CRT Monitor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/crt_monitor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[-10.03, 0.134, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/crt_monitor.glb')
