/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monitor.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monitor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Screen.geometry} material={materials.Display_Mat} />
    </group>
  )
}

useGLTF.preload('/monitor.glb')
