/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/c64_monitor.glb --transform 
Files: public/models/c64_monitor.glb [1MB] > E:\new-portfolio\c64_monitor-transformed.glb [77.22KB] (92%)
Author: hoschu (https://sketchfab.com/hoschu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c64-monitor-b005d2125a1545ad9e0994e0deb5e82e
Title: C64 Monitor
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Model({ image, ...props }) {
  const { nodes, materials } = useGLTF('/models/c64_monitor-transformed.glb')

  if (typeof window !== 'undefined') {
    window.monitorGeom = nodes.Mesh_Default_0.geometry;
    window.THREE = THREE;
  }

  // Using a solid color if no image is provided so it looks like an active CRT
  const texture = useTexture(image || '/img/placeholder.jpg', (tex) => {
    // Drei's useTexture defaults to true, but we explicitly make sure it flips right-side up
    tex.flipY = true;
  })

  // We need to carefully position the plane over the monitor screen
  // These coords are fine-tuned for the 'c64_monitor' bounding box screen area
  return (
    <group {...props} dispose={null}>
      {/* Original monitor body */}
      <mesh geometry={nodes.Mesh_Default_0.geometry} material={materials.Default} />

      {/* Screen texture overlay */}
      <mesh
        // Readjusted Mathematics from screenshot feedback:
        // Y was too low (on the grill), shifting up by ~13 units to hit the screen area centering at 31.5.
        // Z at 65.5 to sit flush against the glass.
        // Rotation X angled backward (-0.15) to match the tilt of the CRT glass.
        // Scale narrowed significantly to ensure the edges don't clip through the plastic sides.
        position={[0, 21, 65.5]}
        rotation={[-0.15, 0, 0]}
        scale={[29, 21.5, 1]}
      >
        <planeGeometry args={[1, 1]} />
        <meshBasicMaterial
          map={texture}
          toneMapped={false}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/c64_monitor-transformed.glb')
