/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/c64_monitor.glb --transform 
Files: public/models/c64_monitor.glb [1MB] > E:\new-portfolio\c64_monitor-transformed.glb [77.22KB] (92%)
Author: hoschu (https://sketchfab.com/hoschu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c64-monitor-b005d2125a1545ad9e0994e0deb5e82e
Title: C64 Monitor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/c64_monitor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Default_0.geometry} material={materials.Default} />
    </group>
  )
}

useGLTF.preload('/models/c64_monitor-transformed.glb')
