/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/crt_monitor.glb 
Author: James.Harness (https://sketchfab.com/James.Harness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crt-monitor-e2dd2887a8904e4fa3d5a32e2935adb9
Title: CRT Monitor
*/

import React, { useState, useEffect, useRef } from 'react'
import { useGLTF, Image } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ image, ...props }) {
  const { nodes, materials } = useGLTF('/models/crt_monitor.glb')
  const screenRef = useRef()

  const [isGlitching, setIsGlitching] = useState(false)

  useEffect(() => {
    if (image) {
      setIsGlitching(true)
      const timer = setTimeout(() => {
        setIsGlitching(false)
        if (screenRef.current) {
          screenRef.current.position.set(0, -5, 115) // Reset baseline
          screenRef.current.material.color.set("#ffffff")
        }
      }, 300)
      return () => clearTimeout(timer)
    }
  }, [image])

  // Native WebGL Glitch Effect (Jittering the mesh itself creates an identical offset tracking effect)
  useFrame(() => {
    if (screenRef.current && isGlitching) {
      const xOffset = (Math.random() - 0.5) * 4;
      const yOffset = -5 + (Math.random() - 0.5) * 2;
      screenRef.current.position.set(xOffset, yOffset, 115);
      screenRef.current.material.color.set("#dddddd");
    }
  })

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <group position={[71.88, -20.78, 0]}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[-10.03, 0.134, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>

      {/* 
        Image component mathematically builds a shader mapping with rounded corners, 
        eliminating arbitrary UV wrap conflicts of RoundedBox geometries. 
        Scale [132, 98] is calculated to fit perfectly inside the black inner bevel of the CRT glass.
      */}
      <Image
        ref={screenRef}
        url={image || '/img/placeholder.jpg'}
        position={[0, -5, 115]}
        scale={[134, 102]}
        radius={0.06}
        toneMapped={false}
      />
    </group>
  )
}

useGLTF.preload('/models/crt_monitor.glb')
