/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monitor.glb 
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'

export function Model({ image, ...props }) {
  const { nodes, materials } = useGLTF('/models/monitor.glb')

  // Refs for dual-plane crossfade
  const screenARef = useRef()
  const screenBRef = useRef()
  const activePlane = useRef('A') // Which plane is currently showing
  const prevImage = useRef(null)

  // Load placeholder as fallback
  const placeholderUrl = '/img/placeholder.jpg'

  // We manage textures imperatively for smooth crossfade
  const textureLoader = useMemo(() => new THREE.TextureLoader(), [])

  // Material A — starts fully opaque
  const matA = useMemo(() => new THREE.MeshBasicMaterial({
    transparent: true,
    opacity: 1,
    toneMapped: false,
    color: '#ffffff',
    depthWrite: false,
  }), [])

  // Material B — starts fully transparent
  const matB = useMemo(() => new THREE.MeshBasicMaterial({
    transparent: true,
    opacity: 0,
    toneMapped: false,
    color: '#ffffff',
    depthWrite: false,
  }), [])

  // Helper to adjust texture to behave like 'object-fit: cover'
  const applyCoverEffect = (tex) => {
    if (!tex.image) return
    const imgWidth = tex.image.width || 1
    const imgHeight = tex.image.height || 1
    // Since the texture is rotated 90 degrees, we swap width and height for aspect calculation
    const imgAspect = imgHeight / imgWidth
    const screenAspect = 1.33 
    
    // Rotate texture
    tex.rotation = -Math.PI / 2
    tex.center.set(0.5, 0.5)
    
    // Fix GLTF texture orientation (flip it back so text isn't mirrored after rotation)
    tex.flipY = false

    if (imgAspect > screenAspect) {
      const scale = screenAspect / imgAspect
      tex.repeat.set(scale, 1)
      // Because it's rotated, offset still works on U or V but the axes are swapped visually
      // Usually keeping offset to (1-scale)/2 centers it correctly from the center point
      tex.offset.set((1 - scale) / 2, 0)
    } else {
      const scale = imgAspect / screenAspect
      tex.repeat.set(1, scale)
      tex.offset.set(0, (1 - scale) / 2)
    }
  }

  // Load initial placeholder texture
  useEffect(() => {
    const tex = textureLoader.load(placeholderUrl, (loadedTex) => {
      loadedTex.colorSpace = THREE.SRGBColorSpace
      loadedTex.minFilter = THREE.LinearFilter
      loadedTex.magFilter = THREE.LinearFilter
      loadedTex.anisotropy = 16
      
      applyCoverEffect(loadedTex)
      
      matA.map = loadedTex
      matA.needsUpdate = true
    })
  }, [])

  // Handle image changes with smooth crossfade
  useEffect(() => {
    const url = image || placeholderUrl
    if (url === prevImage.current) return
    prevImage.current = url

    // Determine which screen is currently hidden (target)
    const isAActive = activePlane.current === 'A'
    const targetMat = isAActive ? matB : matA
    const currentMat = isAActive ? matA : matB
    const currentMesh = isAActive ? screenARef.current : screenBRef.current

    // Load the new texture
    textureLoader.load(url, (loadedTex) => {
      loadedTex.colorSpace = THREE.SRGBColorSpace
      loadedTex.minFilter = THREE.LinearFilter
      loadedTex.magFilter = THREE.LinearFilter
      loadedTex.anisotropy = 16

      applyCoverEffect(loadedTex)

      // Apply to the hidden plane
      targetMat.map = loadedTex
      targetMat.needsUpdate = true

      // Crossfade: fade target in, fade current out
      gsap.to(targetMat, {
        opacity: 1,
        duration: 0.7,
        ease: "power3.out",
      })
      gsap.to(currentMat, {
        opacity: 0,
        duration: 0.7,
        ease: "power3.out",
      })

      // Flip active indicator
      activePlane.current = isAActive ? 'B' : 'A'
    })
  }, [image])

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        {/* ── Chassis ── */}
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} />
        
        {/* 
          ── Screens ── 
          We render two overlapping screen meshes with the exact same geometry to enable crossfading.
          The second screen is pushed forward infinitesimally on the Z axis to avoid Z-fighting.
        */}
        <mesh 
          ref={screenARef}
          geometry={nodes.Screen.geometry} 
          material={matA} 
        />
        
        <mesh 
          ref={screenBRef}
          geometry={nodes.Screen.geometry} 
          material={matB} 
          position={[0, 0, 0.005]} 
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/monitor.glb')
