/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/smartphone.glb --transform 
Files: public/models/smartphone.glb [26.67MB] > E:\new-portfolio\smartphone-transformed.glb [546.08KB] (98%)
Author: Manuel W. (https://sketchfab.com/nebulariser)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smartphone-380280333c9f4fb8a21a53d18f6789e6
Title: Smartphone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/smartphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.539, 0.502, 0.077]} rotation={[1.233, -0.19, 0.494]} scale={[1, 0.672, 1]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} rotation={[1.233, -0.19, 0.494]} />
    </group>
  )
}

useGLTF.preload('/smartphone-transformed.glb')
