/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/smartphone.glb --transform 
Files: public/models/smartphone.glb [26.67MB] > E:\new-portfolio\smartphone-transformed.glb [546.08KB] (98%)
Author: Manuel W. (https://sketchfab.com/nebulariser)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smartphone-380280333c9f4fb8a21a53d18f6789e6
Title: Smartphone
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/smartphone-transformed.glb')
  const screenMatRef = useRef()

  // Clone the original screen material and modify it for a vibrant look
  const screenMaterial = useMemo(() => {
    const mat = materials.PaletteMaterial001.clone()
    mat.color = new THREE.Color('#08081a')
    mat.emissive = new THREE.Color('#1a1a3e')
    mat.emissiveIntensity = 0.6
    mat.metalness = 0.85
    mat.roughness = 0.15
    return mat
  }, [materials])

  // Animate the screen with a slow pulsing color shift
  useFrame((state) => {
    const t = state.clock.elapsedTime
    // Shift hue between deep blue and teal
    const hue = 0.6 + Math.sin(t * 0.4) * 0.08
    const lightness = 0.12 + Math.sin(t * 0.8) * 0.04
    screenMaterial.emissive.setHSL(hue, 0.7, lightness)
    screenMaterial.emissiveIntensity = 0.5 + Math.sin(t * 1.2) * 0.15
  })

  return (
    <group {...props} dispose={null}>
      {/* Screen — animated dark material */}
      <mesh
        geometry={nodes.Object_4.geometry}
        material={screenMaterial}
        position={[0.539, 0.502, 0.077]}
        rotation={[1.233, -0.19, 0.494]}
        scale={[1, 0.672, 1]}
      />
      {/* Phone body/frame — original */}
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.PaletteMaterial002}
        rotation={[1.233, -0.19, 0.494]}
      />
    </group>
  )
}

useGLTF.preload('/models/smartphone-transformed.glb')
