/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/smartphone.glb --transform 
Files: public/models/smartphone.glb [26.67MB] > E:\new-portfolio\smartphone-transformed.glb [546.08KB] (98%)
Author: Manuel W. (https://sketchfab.com/nebulariser)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smartphone-380280333c9f4fb8a21a53d18f6789e6
Title: Smartphone
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/smartphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* 3D Geometries */}
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.539, 0.502, 0.077]} rotation={[1.233, -0.19, 0.494]} scale={[1, 0.672, 1]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} rotation={[1.233, -0.19, 0.494]} />

      {/* HTML Render Target mapped to the tilted orientation of the meshes */}
      <Html
        transform
        distanceFactor={1.3}
        position={[0, 0, 0.08]} // A bit forward to sit on the glass
        rotation={[1.233, -0.19, 0.494]}
        zIndexRange={[100, 0]}
        occlude="blending"
      >
        <div
          className="w-[280px] h-[550px] bg-neutral-950 rounded-[2.5rem] overflow-hidden flex flex-col items-center justify-center pointer-events-none select-none relative shadow-inner [mask-image:linear-gradient(to_bottom,black,transparent)]"
          style={{ opacity: props.screenOpacity ?? 1 }}
        >
          {/* Soft internal glass glare */}
          <div className="absolute top-0 left-0 w-full h-[30%] bg-gradient-to-b from-white/10 to-transparent skew-y-12 translate-y-[-50%] pointer-events-none" />

          {props.children}
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/models/smartphone-transformed.glb')
