/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone_17_pro.glb -o src/components/models/Iphone17Pro.jsx 
Author: Ranguel (https://sketchfab.com/Ranguel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-17-pro-4541aa8a28324b33a2baaf81d263aaec
Title: iPhone 17 Pro
*/

import React, { useMemo, useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { SKILLS_STATS, EXPERIENCE } from '@/assets/data/SKILLS'

// ── Paint the phone screen onto a Canvas2D texture ──
function createScreenTexture() {
  const W = 1024
  const H = 2218
  const canvas = document.createElement('canvas')
  canvas.width = W
  canvas.height = H
  const ctx = canvas.getContext('2d')
  const scale = W / 393
  const s = (v) => v * scale
  const padX = s(20)

  // 1. Clear with fully transparent background
  ctx.clearRect(0, 0, W, H)

  // 2. Rounded clip (this combined with alphaTest: 0.5 in the material 
  //    makes the corners perfectly round without z-sorting issues)
  const cornerR = s(55)
  ctx.save()
  roundRect(ctx, 0, 0, W, H, cornerR)
  ctx.clip()

  // ── Premium Dark Mode Background ──
  const bgGrad = ctx.createLinearGradient(0, 0, 0, H)
  bgGrad.addColorStop(0, '#0a0a0b')
  bgGrad.addColorStop(1, '#111114')
  ctx.fillStyle = bgGrad
  ctx.fillRect(0, 0, W, H)

  // Subtle top glow
  const glow = ctx.createRadialGradient(W/2, 0, 0, W/2, 0, s(400))
  glow.addColorStop(0, 'rgba(80, 80, 90, 0.15)')
  glow.addColorStop(1, 'rgba(10, 10, 11, 0)')
  ctx.fillStyle = glow
  ctx.fillRect(0, 0, W, H)

  // ── Status bar ──
  ctx.fillStyle = '#ffffff'
  ctx.font = `600 ${s(15)}px -apple-system, system-ui, sans-serif`
  ctx.textBaseline = 'top'
  ctx.fillText('9:41', s(32), s(16))
  
  const batX = W - s(58)
  ctx.fillRect(batX, s(18), s(24), s(11))
  ctx.fillStyle = '#ffffff'
  roundRect(ctx, batX - s(20), s(17), s(16), s(13), s(4))
  ctx.fill()

  // ── "Overview." title ──
  ctx.fillStyle = '#ffffff'
  ctx.font = `800 ${s(48)}px -apple-system, system-ui, sans-serif`
  ctx.fillText('Overview.', padX, s(60))

  // Accent color for premium feel
  const accent = '#D4FF3F' // Neon lime-yellow

  // ── Stats Grid (2×2) ──
  const statsY = s(140)
  const gap = s(16)
  const cardW = (W - padX * 2 - gap) / 2
  const cardH = cardW * 0.95

  SKILLS_STATS.forEach((stat, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const x = padX + col * (cardW + gap)
    const y = statsY + row * (cardH + gap)

    // Card bg
    ctx.fillStyle = 'rgba(25, 25, 28, 0.95)'
    roundRect(ctx, x, y, cardW, cardH, s(24))
    ctx.fill()
    
    // Glassmorphism border
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)'
    ctx.lineWidth = s(2)
    roundRect(ctx, x, y, cardW, cardH, s(24))
    ctx.stroke()

    // Dot accent
    ctx.fillStyle = accent
    ctx.beginPath()
    ctx.arc(x + s(24), y + s(28), s(3), 0, Math.PI * 2)
    ctx.fill()

    // Value
    ctx.fillStyle = '#ffffff'
    const isLong = stat.value.length > 5
    ctx.font = `800 ${isLong ? s(28) : s(36)}px -apple-system, system-ui, sans-serif`
    ctx.fillText(stat.value, x + s(20), y + s(52))

    // Label
    ctx.fillStyle = '#8a8a93'
    ctx.font = `600 ${s(11)}px -apple-system, system-ui, sans-serif`
    ctx.fillText(stat.label.toUpperCase(), x + s(20), y + cardH - s(32))
  })

  // ── Experience Preview ──
  const xpY = statsY + 2 * (cardH + gap) + s(20)
  
  ctx.fillStyle = accent
  ctx.beginPath()
  ctx.arc(padX + s(8), xpY + s(6), s(4), 0, Math.PI * 2)
  ctx.fill()
  
  ctx.fillStyle = '#ffffff'
  ctx.font = `700 ${s(12)}px -apple-system, system-ui, sans-serif`
  ctx.fillText('EXPERIENCE', padX + s(20), xpY)

  const xpCardY = xpY + s(24)
  const xpCardH = H - xpCardY - s(24)

  ctx.fillStyle = 'rgba(25, 25, 28, 0.95)'
  roundRect(ctx, padX, xpCardY, W - padX * 2, xpCardH, s(24))
  ctx.fill()
  
  ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)'
  ctx.lineWidth = s(2)
  roundRect(ctx, padX, xpCardY, W - padX * 2, xpCardH, s(24))
  ctx.stroke()

  let yOff = xpCardY + s(24)
  EXPERIENCE.forEach((xp, idx) => {
    const iconX = padX + s(20)
    
    // Icon holder
    ctx.fillStyle = 'rgba(255, 255, 255, 0.05)'
    roundRect(ctx, iconX, yOff, s(40), s(40), s(12))
    ctx.fill()
    ctx.fillStyle = '#ffffff'
    ctx.beginPath()
    ctx.arc(iconX + s(20), yOff + s(20), s(4), 0, Math.PI * 2)
    ctx.fill()

    // Title
    ctx.fillStyle = '#ffffff'
    ctx.font = `700 ${s(16)}px -apple-system, system-ui, sans-serif`
    ctx.fillText(xp.company, iconX + s(56), yOff + s(2))

    // Period
    ctx.fillStyle = '#8a8a93'
    ctx.font = `500 ${s(10.5)}px -apple-system, system-ui, sans-serif`
    ctx.fillText(xp.period.toUpperCase(), iconX + s(56), yOff + s(24))

    yOff += s(64)

    // Divider line
    if (idx < EXPERIENCE.length - 1) {
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)'
      ctx.lineWidth = s(1.5)
      ctx.beginPath()
      ctx.moveTo(iconX + s(56), yOff - s(12))
      ctx.lineTo(W - padX - s(24), yOff - s(12))
      ctx.stroke()
    }
  })

  // Bottom dark fade (gradual opacity mask)
  const grad = ctx.createLinearGradient(0, H - s(80), 0, H)
  grad.addColorStop(0, 'rgba(10,10,11,0)')
  grad.addColorStop(1, 'rgba(10,10,11,1)')
  ctx.fillStyle = grad
  ctx.fillRect(0, H - s(80), W, s(80))

  ctx.restore() // End rounded clip

  const tex = new THREE.CanvasTexture(canvas)
  tex.colorSpace = THREE.SRGBColorSpace
  tex.minFilter = THREE.LinearFilter
  tex.magFilter = THREE.LinearFilter
  tex.generateMipmaps = false
  tex.needsUpdate = true
  return tex
}

function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.lineTo(x + w - r, y)
  ctx.quadraticCurveTo(x + w, y, x + w, y + r)
  ctx.lineTo(x + w, y + h - r)
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h)
  ctx.lineTo(x + r, y + h)
  ctx.quadraticCurveTo(x, y + h, x, y + h - r)
  ctx.lineTo(x, y + r)
  ctx.quadraticCurveTo(x, y, x + r, y)
  ctx.closePath()
}

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/iphone_17_pro.glb')
  const screenRef = useRef()

  const screenTexture = useMemo(() => createScreenTexture(), [])

  // MeshBasicMaterial with alphaTest eliminates the "white border" corners completely 
  // by discarding pixels that are transparent. This avoids z-fighting sorting issues!
  const screenMat = useMemo(() => new THREE.MeshBasicMaterial({
    map: screenTexture,
    alphaTest: 0.5, 
    toneMapped: false,
    color: '#ffffff',
  }), [screenTexture])

  // Size and position the screen plane from the Display mesh bounding box
  useEffect(() => {
    if (!screenRef.current) return
    const geo = nodes.Object_55.geometry
    geo.computeBoundingBox()
    const box = geo.boundingBox
    const w = box.max.x - box.min.x
    const h = box.max.y - box.min.y
    const cx = (box.max.x + box.min.x) / 2
    const cy = (box.max.y + box.min.y) / 2
    const cz = box.max.z + 0.0003

    // Shrink horizontal/vertical to sit purely inside the inner black bezel of the glass
    screenRef.current.geometry = new THREE.PlaneGeometry(w * 0.91, h * 0.94)
    screenRef.current.position.set(cx, cy, cz)
  }, [nodes])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Plastic_antena} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Plastic_USB_port} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Camera_filter} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Tint_back_glass} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Metal_Screw} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Frosted_glass} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Tint_back_glass} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Glass} />
      <group position={[0.022, 0.061, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.352, 0.51, 0.352]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials.Lens} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Sapphire_miror} />
      </group>
      <group position={[0.022, 0.061, -0.008]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.003, 1, 1.003]}>
        <mesh geometry={nodes.Object_23.geometry} material={materials.Sapphire_miror} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Mirror_filter} />
      </group>
      <mesh geometry={nodes.Object_16.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Camera_filter} />
      <group position={[0.022, 0.041, -0.008]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.003, 1, 1.003]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.Sapphire_miror} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Mirror_filter} />
      </group>
      <mesh geometry={nodes.Object_26.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Camera_filter} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Lens} position={[0.022, 0.041, -0.006]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.92, 1.568, 0.92]} />
      <group position={[0.004, 0.051, -0.008]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.003, 1, 1.003]}>
        <mesh geometry={nodes.Object_41.geometry} material={materials.Sapphire_miror} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Mirror_filter} />
      </group>
      <mesh geometry={nodes.Object_35.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Camera_filter} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Lens} position={[0.004, 0.051, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.23, 1, 1.23]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Lens} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Camera_filter} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Plastic_LED} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Metal_Screw} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Frame} />
      {/* Original Display mesh (dark glass background inside bezel) */}
      <mesh geometry={nodes.Object_55.geometry} material={materials.Display} />
      {/* Clean overlay plane representing the active illuminated OLED pixels */}
      <mesh ref={screenRef} material={screenMat} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Metal_Screw} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Metal_Screw} />
    </group>
  )
}

useGLTF.preload('/models/iphone_17_pro.glb')
